language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm

script:
  - hexo generate # generate static files

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $hexo
  keep-history: true
  local-dir: public
  on:
    branch: master
  